package com.interpreters.lox;

public enum TokenType {
    LEFT_BRACE, RIGHT_BRACE, LEFT_PAREN, RIGHT_PAREN,
    PLUS, MINUS, STAR, SLASH,

    IDENTIFIER, NUMBER, STRING,

    EQUAL, EQUAL_EQUAL, BANG, BANG_EQUAL,
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,

    SEMICOLON, DOT, QUESTION_MARK, COLON,
    IF, ELSE, FOR, PRINT, RETURN, WHILE, OR, AND, CLASS, FUN, NIL, THIS, SUPER, VAR, BREAK,
    TRUE, FALSE,

    EOF
}
